### ISSUE TITLE
doesnt work in oc 3.0.3.3

### ISSUE THREAD

**Issue by perspolise** [picsouds/opencart_elfinder#1]
image folder is empty in elfinder.

test: xampp and windows 10.

![ssa](https://user-images.githubusercontent.com/19752074/87695480-cb718580-c7a4-11ea-830d-9f77026bddc3.png)

**Comment by picsouds** [comment]
cf. https://github.com/picsouds/opencart_elfinder#configuration, if you not set à HTTP Basic Authentication , just comment the line n° 93 `array( 'pattern'=>'/.+/', 'hidden'=>(isset($_SERVER['PHP_AUTH_USER']))? false : true )`, in  upload/admin/controller/extension/module/elfinderconnector.php.
Work great in opencart 3.0.3.6 -  Xampp 3.2.4 on VBoxVM windows 10.
